#!/bin/bash

RESOURCES_DIR=/vagrant/resources

MYSQL_ROOT_PASSWD="UvwKXqnrfn27CNVz"
MYSQL_HIVE_PASSWD="3MX6fDLN2AQm23bD"
SPARK_VERSION=2.4.5
SPARK_HADOOP_VERSION=2.7
HIVE_VERSION=3.1.2
LIVY_VERSION=0.7.0
HADOOP_VERSION=3.2.1
DOCKER_COMPOSE_VERSION=1.25.4